server:
  port: 7085
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: ibc-cust-fin
  cloud:
    nacos:
      discovery:
#        server-addr: 192.168.164.128:8848
        server-addr: 127.0.0.1:8848
  datasource:
    hikari:
      cachePrepStmts: true
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 20
      minimum-idle: 5
      prepStmtCacheSize: 128
      prepStmtCacheSqlLimit: 1024
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 21MB
      max-request-size: 21MB

ibc:
  message:
    project:
      sender:
        feign: true
